newton-rabbitmq:
  image: rabbitmq:3
  container_name: newton-rabbitmq
  hostname: rabbitmq
  ports:
    - "5672:5672"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.28"
    - "keystone-host:10.199.1.28"
    - "horizon-host:10.199.1.28"
    - "cinder-host:10.199.1.28"
    - "glance-host:10.199.1.28"
    - "nova-host:10.199.1.28"
    - "neutron-host:10.199.1.28"
    - "heat-host:10.199.1.28"
    - "mongo-host:10.199.1.28"
    - "ceil-host:10.199.1.28"
    - "mysql-host:10.199.1.28"
    - "aodh-host:10.199.1.28"

newton-mariadb:
  build: dockerfiles/mariadb
  container_name: newton-mariadb
  hostname: mariadb
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/openstack-mariadb/mysql:/var/lib/mysql
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.28"
    - "keystone-host:10.199.1.28"
    - "horizon-host:10.199.1.28"
    - "cinder-host:10.199.1.28"
    - "glance-host:10.199.1.28"
    - "nova-host:10.199.1.28"
    - "neutron-host:10.199.1.28"
    - "heat-host:10.199.1.28"
    - "mongo-host:10.199.1.28"
    - "ceil-host:10.199.1.28"
    - "mysql-host:10.199.1.28"
    - "aodh-host:10.199.1.28"


newton-keystone:
  build: dockerfiles/keystone
  container_name: newton-keystone
  hostname: keystone
  ports:
    - "5000:5000"
    - "35357:35357"
  env_file:
    - ./env.list
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.28"
    - "keystone-host:10.199.1.28"
    - "horizon-host:10.199.1.28"
    - "cinder-host:10.199.1.28"
    - "glance-host:10.199.1.28"
    - "nova-host:10.199.1.28"
    - "neutron-host:10.199.1.28"
    - "heat-host:10.199.1.28"
    - "mongo-host:10.199.1.28"
    - "ceil-host:10.199.1.28"
    - "mysql-host:10.199.1.28"
    - "aodh-host:10.199.1.28"

newton-glance:
  build: dockerfiles/glance
  container_name: newton-glance
  hostname: glance
  ports:
    - "9292:9292"
  env_file:
    - ./env.list
  #links:
  #  - newton-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.28"
    - "keystone-host:10.199.1.28"
    - "horizon-host:10.199.1.28"
    - "cinder-host:10.199.1.28"
    - "glance-host:10.199.1.28"
    - "nova-host:10.199.1.28"
    - "neutron-host:10.199.1.28"
    - "heat-host:10.199.1.28"
    - "mongo-host:10.199.1.28"
    - "ceil-host:10.199.1.28"
    - "mysql-host:10.199.1.28"
    - "aodh-host:10.199.1.28"

newton-nova:
  build: dockerfiles/nova
  container_name: newton-nova
  hostname: nova
  privileged: true
  ports:
    - "8774:8774"
    - "8775:8775"
    - "6080:6080"
  env_file:
    - ./env.list
  #links:
  #  - newton-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.28"
    - "keystone-host:10.199.1.28"
    - "horizon-host:10.199.1.28"
    - "cinder-host:10.199.1.28"
    - "glance-host:10.199.1.28"
    - "nova-host:10.199.1.28"
    - "neutron-host:10.199.1.28"
    - "heat-host:10.199.1.28"
    - "mongo-host:10.199.1.28"
    - "ceil-host:10.199.1.28"
    - "mysql-host:10.199.1.28"
    - "aodh-host:10.199.1.28"

newton-neutron:
  build: dockerfiles/neutron
  container_name: newton-neutron
  hostname: neutron
  ports:
    - "9696:9696"
  env_file:
    - ./env.list
  #links:
  #  - newton-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.28"
    - "keystone-host:10.199.1.28"
    - "horizon-host:10.199.1.28"
    - "cinder-host:10.199.1.28"
    - "glance-host:10.199.1.28"
    - "nova-host:10.199.1.28"
    - "neutron-host:10.199.1.28"
    - "heat-host:10.199.1.28"
    - "mongo-host:10.199.1.28"
    - "ceil-host:10.199.1.28"
    - "mysql-host:10.199.1.28"
    - "aodh-host:10.199.1.28"

newton-heat:
  build: dockerfiles/heat
  container_name: newton-heat
  hostname: heat
  ports:
    - "8000:8000"
    - "8004:8004"
  env_file:
    - ./env.list
  #links:
  #  - newton-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.28"
    - "keystone-host:10.199.1.28"
    - "horizon-host:10.199.1.28"
    - "cinder-host:10.199.1.28"
    - "glance-host:10.199.1.28"
    - "nova-host:10.199.1.28"
    - "neutron-host:10.199.1.28"
    - "heat-host:10.199.1.28"
    - "mongo-host:10.199.1.28"
    - "ceil-host:10.199.1.28"
    - "mysql-host:10.199.1.28"
    - "aodh-host:10.199.1.28"

newton-clients:
  build: dockerfiles/openstack_clients
  container_name: newton-clients
  hostname: newton-clients
  ports:
    - "22222:22"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.28"
    - "keystone-host:10.199.1.28"
    - "horizon-host:10.199.1.28"
    - "cinder-host:10.199.1.28"
    - "glance-host:10.199.1.28"
    - "nova-host:10.199.1.28"
    - "neutron-host:10.199.1.28"
    - "heat-host:10.199.1.28"
    - "mongo-host:10.199.1.28"
    - "ceil-host:10.199.1.28"
    - "mysql-host:10.199.1.28"
    - "aodh-host:10.199.1.28"


newton-horizon:
  build: dockerfiles/horizon
  container_name: newton-horizon
  hostname: horizon
  ports:
    - "8888:80"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.28"
    - "keystone-host:10.199.1.28"
    - "horizon-host:10.199.1.28"
    - "cinder-host:10.199.1.28"
    - "glance-host:10.199.1.28"
    - "nova-host:10.199.1.28"
    - "neutron-host:10.199.1.28"
    - "heat-host:10.199.1.28"
    - "mongo-host:10.199.1.28"
    - "ceil-host:10.199.1.28"
    - "mysql-host:10.199.1.28"
    - "aodh-host:10.199.1.28"

newton-ceilometer:
  build: dockerfiles/ceilometer
  container_name: newton-ceilometer
  hostname: ceilometer
  ports:
    - "8777:8777"
  env_file:
    - ./env.list
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.28"
    - "keystone-host:10.199.1.28"
    - "horizon-host:10.199.1.28"
    - "cinder-host:10.199.1.28"
    - "glance-host:10.199.1.28"
    - "nova-host:10.199.1.28"
    - "neutron-host:10.199.1.28"
    - "heat-host:10.199.1.28"
    - "mongo-host:10.199.1.28"
    - "ceil-host:10.199.1.28"
    - "mysql-host:10.199.1.28"
    - "aodh-host:10.199.1.28"

newton-mongodb:
  build: dockerfiles/mongodb
  container_name: newton-mongodb
  hostname: mongodb
  ports:
    - "27017:27017"
  env_file:
    - ./env.list
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.28"
    - "keystone-host:10.199.1.28"
    - "horizon-host:10.199.1.28"
    - "cinder-host:10.199.1.28"
    - "glance-host:10.199.1.28"
    - "nova-host:10.199.1.28"
    - "neutron-host:10.199.1.28"
    - "heat-host:10.199.1.28"
    - "mongo-host:10.199.1.28"
    - "ceil-host:10.199.1.28"
    - "mysql-host:10.199.1.28"
    - "aodh-host:10.199.1.28"
