install_rabbitmq:
  image: rabbitmq:3
  container_name: openstack-rabbitmq
  hostname: rabbitmq
  ports:
    - "5672:5672"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

openstack-mariadb:
  build: dockerfiles/mariadb
  container_name: openstack-mariadb
  hostname: mariadb
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/openstack-mariadb/mysql:/var/lib/mysql
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"


openstack-keystone:
  build: dockerfiles/keystone
  container_name: openstack-keystone
  hostname: keystone
  ports:
    - "5000:5000"
    - "35357:35357"
  env_file:
    - ./env.list
  links:
    - openstack-mariadb
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

openstack-glance:
  build: dockerfiles/glance
  container_name: openstack-glance
  hostname: glance
  ports:
    - "9292:9292"
  env_file:
    - ./env.list
  links:
    - openstack-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

openstack-nova:
  build: dockerfiles/nova
  container_name: openstack-nova
  hostname: nova
  privileged: true
  ports:
    - "8774:8774"
    - "8775:8775"
    - "6080:6080"
  env_file:
    - ./env.list
  links:
    - openstack-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

openstack-neutron:
  build: dockerfiles/neutron
  container_name: openstack-neutron
  hostname: neutron
  ports:
    - "9696:9696"
  env_file:
    - ./env.list
  links:
    - openstack-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

openstack-heat:
  build: dockerfiles/heat
  container_name: openstack-heat
  hostname: heat
  ports:
    - "8000:8000"
    - "8004:8004"
  env_file:
    - ./env.list
  links:
    - openstack-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

openstack-clients:
  build: dockerfiles/openstack_clients
  container_name: openstack-clients
  hostname: openstack-clients
  ports:
    - "22222:22"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"


openstack-horizon:
  build: dockerfiles/horizon
  container_name: openstack-horizon
  hostname: horizon
  ports:
    - "8888:80"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

os-network-node01:
  build: dockerfiles/network_node
  container_name: openstack-net01
  hostname: net01
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"
    - "netnode-overlay-ip:10.199.5.221"
