openstack-rabbitmq:
  image: rabbitmq:3
  container_name: openstack-rabbitmq
  hostname: rabbitmq
  ports:
    - "5672:5672"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:192.168.2.253"
    - "keystone-host:192.168.2.253"
    - "horizon-host:192.168.2.253"
    - "cinder-host:192.168.2.253"
    - "glance-host:192.168.2.253"
    - "nova-host:192.168.2.253"
    - "neutron-host:192.168.2.253"
    - "heat-host:192.168.2.253"
    - "mongo-host:192.168.2.253"
    - "ceil-host:192.168.2.253"
    - "mysql-host:192.168.2.253"

openstack-mariadb:
  build: dockerfiles/mariadb
  container_name: openstack-mariadb
  hostname: mariadb
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/openstack-mariadb/mysql:/var/lib/mysql
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:192.168.2.253"
    - "keystone-host:192.168.2.253"
    - "horizon-host:192.168.2.253"
    - "cinder-host:192.168.2.253"
    - "glance-host:192.168.2.253"
    - "nova-host:192.168.2.253"
    - "neutron-host:192.168.2.253"
    - "heat-host:192.168.2.253"
    - "mongo-host:192.168.2.253"
    - "ceil-host:192.168.2.253"
    - "mysql-host:192.168.2.253"


openstack-keystone:
  build: dockerfiles/keystone
  container_name: openstack-keystone
  hostname: keystone
  ports:
    - "5000:5000"
    - "35357:35357"
  env_file:
    - ./env.list
  links:
    - openstack-mariadb
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:192.168.2.253"
    - "keystone-host:192.168.2.253"
    - "horizon-host:192.168.2.253"
    - "cinder-host:192.168.2.253"
    - "glance-host:192.168.2.253"
    - "nova-host:192.168.2.253"
    - "neutron-host:192.168.2.253"
    - "heat-host:192.168.2.253"
    - "mongo-host:192.168.2.253"
    - "ceil-host:192.168.2.253"
    - "mysql-host:192.168.2.253"

openstack-glance:
  build: dockerfiles/glance
  container_name: openstack-glance
  hostname: glance
  ports:
    - "9292:9292"
  env_file:
    - ./env.list
  links:
    - openstack-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:192.168.2.253"
    - "keystone-host:192.168.2.253"
    - "horizon-host:192.168.2.253"
    - "cinder-host:192.168.2.253"
    - "glance-host:192.168.2.253"
    - "nova-host:192.168.2.253"
    - "neutron-host:192.168.2.253"
    - "heat-host:192.168.2.253"
    - "mongo-host:192.168.2.253"
    - "ceil-host:192.168.2.253"
    - "mysql-host:192.168.2.253"

openstack-nova:
  build: dockerfiles/nova
  container_name: openstack-nova
  hostname: nova
  privileged: true
  ports:
    - "8774:8774"
    - "8775:8775"
    - "6080:6080"
  env_file:
    - ./env.list
  links:
    - openstack-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:192.168.2.253"
    - "keystone-host:192.168.2.253"
    - "horizon-host:192.168.2.253"
    - "cinder-host:192.168.2.253"
    - "glance-host:192.168.2.253"
    - "nova-host:192.168.2.253"
    - "neutron-host:192.168.2.253"
    - "heat-host:192.168.2.253"
    - "mongo-host:192.168.2.253"
    - "ceil-host:192.168.2.253"
    - "mysql-host:192.168.2.253"

openstack-neutron:
  build: dockerfiles/neutron
  container_name: openstack-neutron
  hostname: neutron
  ports:
    - "9696:9696"
  env_file:
    - ./env.list
  links:
    - openstack-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:192.168.2.253"
    - "keystone-host:192.168.2.253"
    - "horizon-host:192.168.2.253"
    - "cinder-host:192.168.2.253"
    - "glance-host:192.168.2.253"
    - "nova-host:192.168.2.253"
    - "neutron-host:192.168.2.253"
    - "heat-host:192.168.2.253"
    - "mongo-host:192.168.2.253"
    - "ceil-host:192.168.2.253"
    - "mysql-host:192.168.2.253"

openstack-heat:
  build: dockerfiles/heat
  container_name: openstack-heat
  hostname: heat
  ports:
    - "8000:8000"
    - "8004:8004"
  env_file:
    - ./env.list
  links:
    - openstack-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:192.168.2.253"
    - "keystone-host:192.168.2.253"
    - "horizon-host:192.168.2.253"
    - "cinder-host:192.168.2.253"
    - "glance-host:192.168.2.253"
    - "nova-host:192.168.2.253"
    - "neutron-host:192.168.2.253"
    - "heat-host:192.168.2.253"
    - "mongo-host:192.168.2.253"
    - "ceil-host:192.168.2.253"
    - "mysql-host:192.168.2.253"

openstack-clients:
  build: dockerfiles/openstack_clients
  container_name: openstack-clients
  hostname: openstack-clients
  ports:
    - "22222:22"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:192.168.2.253"
    - "keystone-host:192.168.2.253"
    - "horizon-host:192.168.2.253"
    - "cinder-host:192.168.2.253"
    - "glance-host:192.168.2.253"
    - "nova-host:192.168.2.253"
    - "neutron-host:192.168.2.253"
    - "heat-host:192.168.2.253"
    - "mongo-host:192.168.2.253"
    - "ceil-host:192.168.2.253"
    - "mysql-host:192.168.2.253"


openstack-horizon:
  build: dockerfiles/horizon
  container_name: openstack-horizon
  hostname: horizon
  ports:
    - "8888:80"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:192.168.2.253"
    - "keystone-host:192.168.2.253"
    - "horizon-host:192.168.2.253"
    - "cinder-host:192.168.2.253"
    - "glance-host:192.168.2.253"
    - "nova-host:192.168.2.253"
    - "neutron-host:192.168.2.253"
    - "heat-host:192.168.2.253"
    - "mongo-host:192.168.2.253"
    - "ceil-host:192.168.2.253"
    - "mysql-host:192.168.2.253"

openstack-ceilometer:
  build: dockerfiles/ceilometer
  container_name: openstack-ceilometer
  hostname: ceilometer
  ports:
    - "8777:8777"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:192.168.2.253"
    - "keystone-host:192.168.2.253"
    - "horizon-host:192.168.2.253"
    - "cinder-host:192.168.2.253"
    - "glance-host:192.168.2.253"
    - "nova-host:192.168.2.253"
    - "neutron-host:192.168.2.253"
    - "heat-host:192.168.2.253"
    - "mongo-host:192.168.2.253"
    - "ceil-host:192.168.2.253"
    - "mysql-host:192.168.2.253"

openstack-mongodb:
  build: dockerfiles/mongodb
  container_name: openstack-mongodb
  hostname: mongodb
  ports:
    - "27017:27017"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:192.168.2.253"
    - "keystone-host:192.168.2.253"
    - "horizon-host:192.168.2.253"
    - "cinder-host:192.168.2.253"
    - "glance-host:192.168.2.253"
    - "nova-host:192.168.2.253"
    - "neutron-host:192.168.2.253"
    - "heat-host:192.168.2.253"
    - "mongo-host:192.168.2.253"
    - "ceil-host:192.168.2.253"
    - "mysql-host:192.168.2.253"
