mitaka-rabbitmq:
  image: rabbitmq:3
  container_name: mitaka-rabbitmq
  hostname: rabbitmq
  ports:
    - "5672:5672"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

mitaka-mariadb:
  build: dockerfiles/mariadb
  container_name: mitaka-mariadb
  hostname: mariadb
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/openstack-mariadb/mysql:/var/lib/mysql
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"


mitaka-keystone:
  build: dockerfiles/keystone
  container_name: mitaka-keystone
  hostname: keystone
  ports:
    - "5000:5000"
    - "35357:35357"
  env_file:
    - ./env.list
  links:
    - mitaka-mariadb
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

mitaka-glance:
  build: dockerfiles/glance
  container_name: mitaka-glance
  hostname: glance
  ports:
    - "9292:9292"
  env_file:
    - ./env.list
  links:
    - mitaka-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

mitaka-nova:
  build: dockerfiles/nova
  container_name: mitaka-nova
  hostname: nova
  privileged: true
  ports:
    - "8774:8774"
    - "8775:8775"
    - "6080:6080"
  env_file:
    - ./env.list
  links:
    - mitaka-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

mitaka-neutron:
  build: dockerfiles/neutron
  container_name: mitaka-neutron
  hostname: neutron
  ports:
    - "9696:9696"
  env_file:
    - ./env.list
  links:
    - mitaka-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

mitaka-heat:
  build: dockerfiles/heat
  container_name: mitaka-heat
  hostname: heat
  ports:
    - "8000:8000"
    - "8004:8004"
  env_file:
    - ./env.list
  links:
    - mitaka-keystone
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

mitaka-clients:
  build: dockerfiles/openstack_clients
  container_name: mitaka-clients
  hostname: mitaka-clients
  ports:
    - "22222:22"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"


mitaka-horizon:
  build: dockerfiles/horizon
  container_name: mitaka-horizon
  hostname: horizon
  ports:
    - "8888:80"
  env_file:
    - ./env.list
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

mitaka-ceilometer:
  build: dockerfiles/ceilometer
  container_name: mitaka-ceilometer
  hostname: ceilometer
  ports:
    - "8777:8777"
  env_file:
    - ./env.list
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"

mitaka-mongodb:
  build: dockerfiles/mongodb
  container_name: mitaka-mongodb
  hostname: mongodb
  ports:
    - "27017:27017"
  env_file:
    - ./env.list
  environment:
    - WAIT_SLEEP=1
    - WAIT_LOOPS=100
  extra_hosts:
    - "rabbit-host:10.199.1.220"
    - "keystone-host:10.199.1.220"
    - "horizon-host:10.199.1.220"
    - "cinder-host:10.199.1.220"
    - "glance-host:10.199.1.220"
    - "nova-host:10.199.1.220"
    - "neutron-host:10.199.1.220"
    - "heat-host:10.199.1.220"
    - "mongo-host:10.199.1.220"
    - "ceil-host:10.199.1.220"
    - "mysql-host:10.199.1.220"
