heat_template_version: 2015-04-30
description: A simple server.

# SEE:
# http://docs.openstack.org/developer/heat/template_guide/index.html

resources:

  demo_hot_ping_ssh_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      #description: String
      name: demo_hot_ping_ssh_security_group
      #rules: [{"remote_group_id": String, "port_range_max": Integer, "remote_ip_prefix": String, "protocol": String, "ethertype": String, "port_range_min": Integer, "remote_mode": String, "direction": String}, {"remote_group_id": String, "port_range_max": Integer, "remote_ip_prefix": String, "protocol": String, "ethertype": String, "port_range_min": Integer, "remote_mode": String, "direction": String}, ...]
      rules:
        - protocol: icmp
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
